# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Set up timescaledb
      run: |
          echo "$(whoami)"
          echo "$(pwd)"
          cat /etc/passwd
          sudo mkdir -p /data/v_pgsql
          sudo chown -R 1000:1000 /data/v_pgsql
          #sudo chmod -R 777 /data/v_pgsql
          ls -lah /data
          docker run --network=host -d --restart always --name timescaledb -p 5432:5432 \
          -v /data/v_pgsql:/home/postgres/pgdata/data \
          -e POSTGRES_PASSWORD=P@ssw0rd \
          -e POSTGRES_DB=demo_01 \
          timescale/timescaledb-ha:pg17
          sleep 20
          docker ps -a
          netstat -nptl
          docker logs -n 100 timescaledb
          # docker exec timescaledb psql -c "CREATE DATABASE demo_01;"
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true
